version: '3.8'

services:
  master:
    build:
      context: ./master # Percorso alla directory del Dockerfile del master
      dockerfile: Dockerfile
    container_name: syntranet-master
    ports:
      - "${MASTER_PORT_HOST:5501}:${PORT_CONTAINER_MASTER:5501}" # Mappa la porta (host:container)
    environment:
      # Variabili d'ambiente essenziali prese dal tuo .env
      # Queste sovrascrivono eventuali ENV nel Dockerfile
      - NODE_ENV=production
      - PORT=${PORT_CONTAINER_MASTER:5501}
      - ZK_AA_CALL_SERVER_URL=${ZK_AA_CALL_SERVER_URL} # Da definire nel .env del docker-compose
      - MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY} # Da definire nel .env del docker-compose (CRUCIALE!)
      - BASE_URL=${BASE_URL}                         # Da definire nel .env del docker-compose
      - CONTRACT_NAME=${CONTRACT_NAME:SyntraNetV3}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:0x8c04b4B2db4bC0C6862f9d4543Bf5D3eDACfAF25}
      - K8S_NAMESPACE=${K8S_NAMESPACE:syntracloud}
      - K8S_DEFAULT_STORAGE_CLASS=${K8S_DEFAULT_STORAGE_CLASS:standard}
      - K8S_DEFAULT_STORAGE_SIZE=${K8S_DEFAULT_STORAGE_SIZE:1Gi}
      - K8S_POD_IMAGE=${K8S_POD_IMAGE:debian:bullseye-slim}
      - K8S_MOUNT_PATH=${K8S_MOUNT_PATH:/data}
      - IPFS_API_URL=${IPFS_API_URL:http://127.0.0.1:5001} # Cambia se il tuo IPFS è altrove
      # Aggiungi qui le altre variabili GC_*, DEFAULT_POD_* se necessario
      # GC_INTERVAL_MS=0
      # GC_DELETE_PVC=false
      # GC_USERNAME=
      # GC_PASSWORD=
      # DEFAULT_POD_RAM=100Mi
      # DEFAULT_POD_CPU=100m
    # Se il master ha bisogno di accedere a file locali persistenti (es. per /tmp/syntra_backups se non gestito da K8s volumes)
    # volumes:
    #   - ./master_local_temp_backups:/tmp/syntra_backups # Esempio, adatta il percorso host
    restart: unless-stopped
    # networks:
    #   - syntranet_net # Definisci una rete se master e slave devono comunicare

# networks:
#   syntranet_net:
#     driver: bridge